spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          service-product: #服务的名称，
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            retryer: feign.retryer.default
#            request-interceptors:
#             - org.example.order.interceptor.XTokenRequestInterceptor
feign:
  sentinel:
    enabled: true